on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          npm install -g yarn
          yarn install
          npx cypress install
        env:
          CYPRESS_CACHE_FOLDER: ~/.cache/.yarn/.cypress
      - run: npx cypress run-ct
        env:
          CYPRESS_CACHE_FOLDER: ~/.cache/.yarn/.cypress